name: Test propsed changes to main
on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Update/create jobs
        run: pytest ./tests
